swagger: '2.0'
info: 
  title: EduAfric API Documentation
  description: API documentation for EduAfric. Each request comes with a cookie sent from the client.
  version: 1.0
  contact: 
    email: successakinyemi365@gmail.com
  license:
    name: Apache 2.0
    url: 'http://apache.org/'
host: localhost:9000
basePath: /               
schemes:
  - http
  - https

paths:
  /:
    get:
      summary: Home GET request
      description: The first request to check server
      responses:
        200:
          description: Success

  /api/auth/register:
    post:
      summary: Register new user
      description: Register a user
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - email
              - password
              - firstName
              - lastName
              - confirmPassword
              - accountType
            properties:
              email:
                type: string
              password:
                type: string
              firstName:
                type: string
              lastName:
                type: string
              confirmPassword:
                type: string
              accountType:
                type: string
              fromOrganisation:
                type: boolean *Optional
      responses:
        201: 
          description: Signup successful but account not verified
        400:
          description: User error
        500: 
          description: Server error

  /api/auth/login:
    post:
      summary: User Login
      description: Login a user
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200: 
          description: Signup successful but account not verified
        201: 
          description: Signup successful
        400:
          description: User error
        500: 
          description: Server error

  /api/auth/verifyOtp:
    post:
      summary: Verify User account with OTP
      description: Verify User account
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - otp
            properties:
              otp:
                type: string
      responses:
        200: 
          description: OTP verified Account acitvated
        400:
          description: User error
        500: 
          description: Server error
  
  /api/aiChat/aiChat:
    post:
      summary: Chat With AI Zara (AI conversation bot)
      description: Zara EduAfric AI assistant
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      responses:
        200: 
          description: AI response
        400:
          description: User error
        500: 
          description: Server error
  
  /api/course/newCourse:
    post:
      summary: Endpoint to create new course details by instructors
      description: token is required 
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - title
              - about 
              - desc 
              - overview 
              - category 
              - price 
              - isDiscountAllowed 
              - discountPercentage 
              - coverImage 
              - studentLevel 
              - skillsToGain 
              - language
            properties:
              title:
                type: string (required)
              about:
                type: string (required)
              desc:
                type: string (optional)
              overview:
                type: string (required)
              category:
                type: array (required at least one)
              price:
                type: number (required)
              isDiscountAllowed:
                type: boolean (optional)
              discountPercentage:
                type: number (optional)
              coverImage:
                type: file (required)
              studentLevel:
                type: string (required, ['Beginner', 'Intermediate', 'Advanced'])
              skillsToGain:
                type: array (required at least one)
              language:
                type: string (required)
      responses:
        201: 
          description: Cousre created successfull
        400:
          description: User error
        500: 
          description: Server error
  
  /api/course/updateCourse:
    post:
      summary: Endpoint to update a course details by instructors
      description: token is required 
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - title
              - about 
              - desc 
              - overview 
              - category 
              - price 
              - isDiscountAllowed 
              - discountPercentage 
              - coverImage 
              - studentLevel 
              - skillsToGain 
              - language
            properties:
              title:
                type: string
              about:
                type: string
              desc:
                type: string
              overview:
                type: string
              category:
                type: array
              price:
                type: number
              isDiscountAllowed:
                type: boolean
              discountPercentage:
                type: number
              coverImage:
                type: file
              studentLevel:
                type: string (['Beginner', 'Intermediate', 'Advanced'])
              skillsToGain:
                type: array
              language:
                type: string
      responses:
        200: 
          description: Cousre updated successfull
        400:
          description: User error
        500: 
          description: Server error

  /api/course/getAllCourse:
    get:
      summary: Fetch all courses from database
      description: Fetch all courses from database
      responses:
        200: 
          description: successful 
        400:
          description: User error
        500: 
          description: Server error

  /api/course/getAllCourseCategories:
    get:
      summary: Fetch all courses categories from database
      description: Fetch all courses categories from database
      responses:
        200: 
          description: successful 
        400:
          description: User error
        500: 
          description: Server error

  /api/course/getCourseByCategory/:category:
    get:
      summary: Fetch all courses by categories from database
      description: Fetch all courses by categories from database
      responses:
        200: 
          description: successful 
        400:
          description: User error
        500: 
          description: Server error

  /api/course/getCourse:
    get:
      summary: Fetch single course by Id from database
      description: Fetch single course by Id from database
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - _id
            properties:
              _id(required):
                type: string
      responses:
        200: 
          description: successful 
        400:
          description: User error
        500: 
          description: Server error